TRAIN_DATA = [
    ("Tech stocks are climbing again.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury brands saw a huge increase in sales.", {"entities": [(0, 6, "SECTOR")]}),
    ("Investors are pouring money into tech.", {"entities": [(34, 38, "SECTOR")]}),
    ("Luxury continues to dominate the high-end market.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech is leading the recovery.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury has proven resilient during downturns.", {"entities": [(0, 6, "SECTOR")]}),
    ("Analysts predict strong earnings for tech.", {"entities": [(41, 45, "SECTOR")]}),
    ("Many luxury stocks hit new highs today.", {"entities": [(5, 11, "SECTOR")]}),
    ("Tech and luxury are both outperforming.", {"entities": [(0, 4, "SECTOR"), (9, 15, "SECTOR")]}),
    ("Investors favor tech in the current climate.", {"entities": [(16, 20, "SECTOR")]}),
    ("Luxury is rebounding faster than expected.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech remains volatile but promising.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury stocks have gained momentum.", {"entities": [(0, 6, "SECTOR")]}),
    ("The tech sector saw heavy inflows.", {"entities": [(4, 8, "SECTOR")]}),
    ("Luxury names like LVMH continue to soar.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech companies are hiring aggressively.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury is bouncing back post-pandemic.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech keeps outperforming the market.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury and tech are investor favorites.", {"entities": [(0, 6, "SECTOR"), (11, 15, "SECTOR")]}),
    ("Earnings from tech look promising.", {"entities": [(14, 18, "SECTOR")]}),
    ("Luxury demand is growing in Asia.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech rallied on strong fundamentals.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury trends are shifting post-COVID.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech and luxury both surged today.", {"entities": [(0, 4, "SECTOR"), (9, 15, "SECTOR")]}),
    ("Luxury continues to attract long-term investors.", {"entities": [(0, 6, "SECTOR")]}),
    ("The tech industry remains competitive.", {"entities": [(4, 8, "SECTOR")]}),
    ("Luxury valuations are reaching new highs.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech is expected to post record profits.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury segments show strong recovery.", {"entities": [(0, 6, "SECTOR")]}),
    ("Investors are confident in tech stocks.", {"entities": [(27, 31, "SECTOR")]}),
    ("Luxury has shown impressive growth.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech names dominate the NASDAQ.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury goods are in high demand.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech innovation continues to drive earnings.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury and tech outperform traditional sectors.", {"entities": [(0, 6, "SECTOR"), (11, 15, "SECTOR")]}),
    ("Tech is the star of this quarter.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury products saw record growth.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech’s momentum is not slowing down.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury brands remain resilient.", {"entities": [(0, 6, "SECTOR")]}),
    ("Many are bullish on tech in 2025.", {"entities": [(20, 24, "SECTOR")]}),
    ("Luxury is in a growth phase.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech spending is expected to rise.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury and tech dominate portfolios.", {"entities": [(0, 6, "SECTOR"), (11, 15, "SECTOR")]}),
    ("Tech stocks spiked on earnings news.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury continues to grow.", {"entities": [(0, 6, "SECTOR")]}),
    ("Analysts upgrade tech outlook.", {"entities": [(17, 21, "SECTOR")]}),
    ("Luxury is a stable investment.", {"entities": [(0, 6, "SECTOR")]}),
    ("Big tech continues to expand.", {"entities": [(4, 8, "SECTOR")]}),
    ("Luxury demand drives up share prices.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech firms show solid fundamentals.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury continues to recover.", {"entities": [(0, 6, "SECTOR")]}),
    ("Investors focus on tech innovation.", {"entities": [(20, 24, "SECTOR")]}),
    ("Luxury markets rebound strongly.", {"entities": [(0, 6, "SECTOR")]}),
    ("The tech space is growing fast.", {"entities": [(4, 8, "SECTOR")]}),
    ("Luxury stocks rallied again.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech and luxury see rising demand.", {"entities": [(0, 4, "SECTOR"), (9, 15, "SECTOR")]}),
    ("Luxury brands expand internationally.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech hiring surges globally.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury enters a new bull cycle.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech growth beats expectations.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury is strong in emerging markets.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech leaders outperform benchmarks.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury is surging in Europe.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech stocks are favorites in 2025.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury stocks rebound from dip.", {"entities": [(0, 6, "SECTOR")]}),
    ("Investors eye luxury and tech.", {"entities": [(13, 19, "SECTOR"), (24, 28, "SECTOR")]}),
    ("Tech demand grows post-COVID.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury shows positive signs.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech and luxury sectors are booming.", {"entities": [(0, 4, "SECTOR"), (9, 15, "SECTOR")]}),
    ("Luxury thrives in premium markets.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech is still a strong play.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury stocks gain momentum.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech continues to impress.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury drives holiday sales.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech sees record-breaking Q1.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury is regaining strength.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech is attracting long-term investors.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury performs better than expected.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech is outperforming peers.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury and tech appeal to millennials.", {"entities": [(0, 6, "SECTOR"), (11, 15, "SECTOR")]}),
    ("Tech earnings beat forecasts.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury climbs amid recovery.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech drives market optimism.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury remains attractive to analysts.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech shows no signs of slowing.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury's rebound continues.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech and luxury dominate headlines.", {"entities": [(0, 4, "SECTOR"), (9, 15, "SECTOR")]}),
    ("Luxury and tech are heating up.", {"entities": [(0, 6, "SECTOR"), (11, 15, "SECTOR")]}),
    ("Luxury is one of the hottest bets.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech drives Nasdaq growth.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury demand surprises analysts.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech climbs to all-time highs.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury plays a defensive role.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech continues its rally.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury sees strong seasonal growth.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech momentum builds.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury's outlook is bright.", {"entities": [(0, 6, "SECTOR")]}),
    ("Tech shines in volatile market.", {"entities": [(0, 4, "SECTOR")]}),
    ("Luxury dominates the earnings season.", {"entities": [(0, 6, "SECTOR")]}),
]
